sudo: required
services:
  docker

before_install:
  - docker build -t niniko123/nini-repo -f Dockerfile.dev .

script:
  - docker run -e CI=true niniko123/nini-repo npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: beola
  env: Beola-env
  bucket_name: elasticbeanstalk-us-east-2-992382386439
  bucket_path: beola
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
